export const USER_PATTERNS = {
  CREATE: 'user.create',
  CREATE_LOCAL: 'user.createLocal',
  CREATE_OAUTH: 'user.createOAuth',
  CREATE_ACCOUNT: 'user.createAccount',
  VERIFY_LOCAL: 'user.verifyLocal',
  RESET_CODE: 'user.resetCode',
  FIND_ALL: 'user.findAll',
  FIND_ONE: 'user.findOne',
  FIND_ONE_WITH_PASSWORD: 'user.findOneWithPassword',
  FIND_ONE_GOOGLE_BY_EMAIL: 'user.findOneGoogleByEmail',
  FIND_ONE_BY_EMAIL: 'user.findOneByEmail',
  FIND_ONE_OAUTH: 'user.findOneOAuth',
  UPDATE: 'user.update',
  UPDATE_PASSWORD: 'user.updatePassword',
  REMOVE: 'user.remove',
  VALIDATE: 'user.validate',
};
