import { Injectable } from '@nestjs/common';
import { AmqpConnection } from '@golevelup/nestjs-rabbitmq';
import { CreateTaskDto, UpdateTaskDto, TASK_PATTERNS, TASK_EXCHANGE, EPIC_EXCHANGE, EPIC_PATTERNS, EpicStatus, GetTasksByTeamDto, BaseTaskFilterDto } from '@app/contracts';
import { unwrapRpcResult } from '../common/helper/rpc';
import { Priority } from '@app/contracts/enums/priority.enum';

@Injectable()
export class TaskService {

  constructor(
    private readonly amqp: AmqpConnection,

  ) { }

  async create(createTaskDto: CreateTaskDto) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.CREATE,
      payload: createTaskDto,
    }));
  }

  async createMany(createTaskDtos: CreateTaskDto[], epicTitle: string, userId: string) {
    console.log(createTaskDtos)
    const projectId = createTaskDtos[0]?.projectId;

    const newEpic = await unwrapRpcResult(
      await this.amqp.request({
        exchange: EPIC_EXCHANGE,
        routingKey: EPIC_PATTERNS.CREATE,
        payload: {
          title: epicTitle,
          projectId,
          description: `Generated by AI Architect for objective: ${epicTitle}`,
          status: EpicStatus.TODO,
          priority: Priority.MEDIUM
        },
      }),
    );

    const epicId = newEpic.id;

    const tasksWithEpic = createTaskDtos.map(task => ({
      ...task,
      epicId: epicId,
      reporterId: userId
    }));

    return unwrapRpcResult(
      await this.amqp.request({
        exchange: TASK_EXCHANGE,
        routingKey: TASK_PATTERNS.CREATE_MANY,
        payload: tasksWithEpic,
      }),
    );
  }

  async deleteMany(taskIds: string[], userId: string) {
    return unwrapRpcResult(
      await this.amqp.request({
        exchange: TASK_EXCHANGE,
        routingKey: TASK_PATTERNS.DELETE_MANY,
        payload: { taskIds, userId },
      }),
    );
  }

  async updateMany(taskIds: string[], updateTaskDto: UpdateTaskDto, userId: string) {
    return unwrapRpcResult(
      await this.amqp.request({
        exchange: TASK_EXCHANGE,
        routingKey: TASK_PATTERNS.UPDATE_MANY,
        payload: { taskIds, updateTaskDto, userId },
      }),
    );
  }

  async getStatByProjectId(userId: string, projectId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.GET_STATS,
      payload: { userId, projectId },
    }));
  }

  async findAllByProjectId(userId: string, filters: BaseTaskFilterDto) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ALL,
      payload: { userId, filters },
    }));
  }

  async findOne(id: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ONE,
      payload: { id },
    }));
  }

  async update(id: string, updateTaskDto: UpdateTaskDto, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.UPDATE,
      payload: { id, updateTaskDto, userId },
    }));
  }

  async remove(id: string, teamId: string, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.REMOVE,
      payload: { id, teamId, userId },
    }));
  }

  async addFiles(taskId: string, fileIds: string[], userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.ADD_FILES,
      payload: { taskId, fileIds, userId },
    }));
  }

  async removeFile(taskId: string, fileId: string, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.REMOVE_FILE,
      payload: { taskId, fileId, userId },
    }));
  }

  async findLabelsByTaskId(taskId: string, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ALL_LABELS_BY_TASK_ID,
      payload: { taskId, userId },
    }));
  }


  async getAllTaskLabel(projectId: string, teamId: string, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.GET_ALL_TASK_LABEL,
      payload: { projectId, teamId, userId },
    }))
  }

  async handleLabelDeleted(labelId: string, userId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.HANDLE_LABEL_DELETED,
      payload: { id: labelId, userId },
    }));
  }

  async suggestTask(userId: string, query: string, projectId: string, sprintId: string, teamId: string): Promise<string[]> {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.SUGGEST_TASK,
      payload: { userId, query, projectId, sprintId, teamId },
    }));
  }

  async findAllByTeamId(userId: string, filters: BaseTaskFilterDto) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ALL,
      payload: { userId, filters },
    }));
  }
}