import { Injectable } from '@nestjs/common';
import { AmqpConnection } from '@golevelup/nestjs-rabbitmq';
import { CreateTaskDto, UpdateTaskDto, TASK_PATTERNS, TASK_EXCHANGE, EPIC_EXCHANGE, EPIC_PATTERNS, EpicStatus } from '@app/contracts';
import { unwrapRpcResult } from '../common/helper/rpc';
import { Priority } from '@app/contracts/enums/priority.enum';

@Injectable()
export class TaskService {

  constructor(
    private readonly amqp: AmqpConnection,

  ) { }

  async create(createTaskDto: CreateTaskDto) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.CREATE,
      payload: createTaskDto,
    }));
  }

  async createMany(createTaskDtos: CreateTaskDto[], epicTitle: string) {
    console.log(createTaskDtos)
    const projectId = createTaskDtos[0]?.projectId;

    const newEpic = await unwrapRpcResult(
      await this.amqp.request({
        exchange: EPIC_EXCHANGE,
        routingKey: EPIC_PATTERNS.CREATE,
        payload: {
          title: epicTitle,
          projectId,
          description: `Generated by AI Architect for objective: ${epicTitle}`,
          status: EpicStatus.TODO,
          priority: Priority.MEDIUM
        },
      }),
    );

    const epicId = newEpic.id;

    const tasksWithEpic = createTaskDtos.map(task => ({
      ...task,
      epicId: epicId
    }));

    return unwrapRpcResult(
      await this.amqp.request({
        exchange: TASK_EXCHANGE,
        routingKey: TASK_PATTERNS.CREATE_MANY,
        payload: tasksWithEpic,
      }),
    );
  }

  async findAllByProjectId(projectId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ALL,
      payload: { projectId },
    }));
  }

  async findOne(id: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ONE,
      payload: { id },
    }));
  }

  async update(id: string, updateTaskDto: UpdateTaskDto) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.UPDATE,
      payload: { id, updateTaskDto },
    }));
  }

  async remove(id: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.REMOVE,
      payload: { id },
    }));
  }

  async addFiles(taskId: string, fileIds: string[]) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.ADD_FILES,
      payload: { taskId, fileIds },
    }));
  }

  async findLabelsByTaskId(taskId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.FIND_ALL_LABELS_BY_TASK_ID,
      payload: { taskId },
    }));
  }


  async getAllTaskLabel(projectId: string) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.GET_ALL_TASK_LABEL,
      payload: { projectId },
    }))
  }

  async handleLabelDeleted(payload: { labelId: string }) {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.HANDLE_LABEL_DELETED,
      payload: { id: payload.labelId },
    }));
  }

  async suggestTask(userId: string, query: string, projectId: string, sprintId: string, teamId: string): Promise<string[]> {
    return unwrapRpcResult(await this.amqp.request({
      exchange: TASK_EXCHANGE,
      routingKey: TASK_PATTERNS.SUGGEST_TASK,
      payload: { userId, query, projectId, sprintId, teamId },
    }));
  }
}