export const AUTH_PATTERN = {
  INFO: 'auth.info',
  LOGIN: 'auth.login',
  VERIFY_LOCAL: 'auth.verifyLocal',
  VERIFY_LOCAL_TOKEN: 'auth.verifyToken',
  VERIFY_FORGOT_PASSWORD: 'auth.verifyForgotPassword',
  VERIFY_FORGOT_PASSWORD_TOKEN: 'auth.verifyForgotPasswordToken',
  VERIFY_EMAIL: 'auth.verifyEmail',
  RESET_VERIFICATION_CODE: 'auth.resetVerificationCode',
  RESET_CODE: 'auth.resetCode',
  FORGET_PASSWORD: 'auth.forgetPassword',
  CHANGE_PASSWORD: 'auth.changePassword',
  RESET_PASSWORD_CONFIRM: 'auth.resetPasswordConfirm',
  GOOGLE_CALLBACK: 'auth.googleCallback',
  CREATE_ACCESS_TOKEN: 'auth.createAccessToken',
  VALIDATE_TOKEN: 'auth.validateToken',
  REGISTER: 'auth.register',
  LOGOUT: 'auth.logout',
  LOGOUT_ALL: 'auth.logoutAll',
  REFRESH: 'auth.refresh',
};
