export const AUTH_PATTERN = {
  INFO: 'auth.info',
  LOGIN: 'auth.login',
  VERIFY_LOCAL: 'auth.verifyLocal',
  VERIFY_LOCAL_TOKEN: 'auth.verifyToken',
  RESET_CODE: 'auth.resetCode',
  FORGET_PASSWORD: 'auth.forgetPassword',
  RESET_PASSWORD: 'auth.resetPassword',
  GOOGLE_CALLBACK: 'auth.googleCallback',
  CREATE_ACCESS_TOKEN: 'auth.createAccessToken',
  VALIDATE_TOKEN: 'auth.validateToken',
  REGISTER: 'auth.register',
  LOGOUT: 'auth.logout',
  LOGOUT_ALL: 'auth.logoutAll',
  REFRESH: 'auth.refresh',
};
