export const CHATBOT_PATTERN = {
    ASK_QUESTION: 'ask_question',
    PROCESS_DOCUMENT: 'process_document',
    SUMMARIZE_DOCUMENT: 'summarize_document',
    RESPONSE_CHUNK: 'chatbot.response_chunk',
    RESPONSE_ERROR: 'chatbot.response_error',
    RESPONSE_END: 'chatbot.response_end',
    STREAM_RESPONSE: 'rag_response',
    UPLOAD_FILE: 'chatbot.upload_file',
    GET_FILES_BY_USER_ID: 'chatbot.get_files_by_user_id',
    DELETE_FILE: 'chatbot.delete_file',
    FIND_CONVERSATIONS: 'chatbot.find_conversations',
    FIND_CONVERSATION: 'chatbot.find_conversation',
    DELETE_CONVERSATION: 'chatbot.delete_conversation',
};