FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig*.json nest-cli.json ./
RUN npm ci
COPY apps/ apps/
COPY libs/ libs/
ARG APP_NAME
RUN npx nest build ${APP_NAME}

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force
ARG APP_NAME
RUN if [ "$APP_NAME" = "gmail" ]; then \
    npm install --no-save @css-inline/css-inline-linux-x64-musl; \
    else \
    echo "Skipping optional packages for $APP_NAME"; \
    fi
COPY --from=builder /app/dist/apps/${APP_NAME} ./dist
CMD ["node", "dist/main"]