# Source - https://stackoverflow.com/a/74817420
# Posted by Ralle Mc Black
# Retrieved 2025-11-29, License - CC BY-SA 4.0

###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine As development
USER root
# Create app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY  . .
RUN npm run start:all

# Use the node user from the image (instead of the root user)
USER node
