FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/
COPY main.py /app/
COPY consumer.py /app/

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt