export const CHAT_PATTERN = {
  CREATE: 'chat.createConversation',
  CREATE_MESSAGE: 'chat.createMessage',
  CREATE_DIRECT_MESSAGE: 'chat.createDirectMessage',
  GET: 'chat.getConversation',
  GET_CONVERSATION_BY_ID: 'chat.getConversationById',
  GET_CONVERSATION_BY_TEAM_ID: 'chat.getConversationByTeamId',
  GET_MESSAGES: 'chat.getMessagesFromConversation',
  GET_ALL_MESSAGES: 'chat.getAllMessages',
  UPDATE_USER: 'chat.updateUser',
  LEAVE_TEAM: 'chat.leaveTeam',
  REMOVE_MEMBER: 'chat.removeMember',
  ADD_MEMBER: 'chat.addMember',
  SEARCH_MESSAGES: 'chat.searchMessages',
};
