export const VIDEO_CHAT_PATTERN = {
  CREATE_CALL: 'video_chat.call.create',
  GET_HISTORY: 'video_chat.history.get',
  GET_HISTORY_BY_ROOM: 'video_chat.history.room.get',
  JOIN_ROOM: 'video_chat.room.join',
  SEND_TRANSCRIPT: 'video_chat.transcript.send',
  KICK_USER: 'video_chat.user.kick',
  UNKICK_USER: 'video_chat.user.unkick',
  RECEIVE_TRANSCRIPT: 'video_chat.transcript.receive',
  PROCESS_TRANSCRIPT: 'video_chat.transcript.process',
  LEAVE_ROOM: 'video_chat.room.leave',
  END_CALL: 'video_chat.call.end',
  OFFER: 'video_chat.signal.offer',
  ANSWER: 'video_chat.signal.answer',
  ICE_CANDIDATE: 'video_chat.signal.ice',
  DISCONNECT: 'video_chat.client.disconnect',
};