export enum StatusErrorCode {
  STATUS_NOT_FOUND = 'STATUS_NOT_FOUND',
  STATUS_ALREADY_EXISTS = 'STATUS_ALREADY_EXISTS',
  INVALID_STATUS_DATA = 'INVALID_STATUS_DATA',
  UNAUTHORIZED_STATUS_ACCESS = 'UNAUTHORIZED_STATUS_ACCESS',
  STATUS_IN_USE = 'STATUS_IN_USE',
  INVALID_STATUS_ORDER = 'INVALID_STATUS_ORDER',
}
