export enum ListErrorCode {
  LIST_NOT_FOUND = 'LIST_NOT_FOUND',
  LIST_ALREADY_EXISTS = 'LIST_ALREADY_EXISTS',
  INVALID_LIST_DATA = 'INVALID_LIST_DATA',
  UNAUTHORIZED_LIST_ACCESS = 'UNAUTHORIZED_LIST_ACCESS',
  LIST_IN_USE = 'LIST_IN_USE',
  INVALID_LIST_ORDER = 'INVALID_LIST_ORDER',
}
