export const EVENTS = {
  REGISTER: 'events.register',
  LOGIN: 'events.login',
  USER_UPDATED: 'events.user.updated',
  CREATE_TEAM: 'events.create.team',
  CREATE_CONVERSATION:'events.create.conversation',
  ADD_MEMBER: 'events.add.member',
  REMOVE_MEMBER: 'events.remove.member',
  LEAVE_TEAM: 'events.leave.team',
  REMOVE_TEAM: 'events.remove.team',
  MEMBER_ROLE_CHANGED: 'events.member.role.changed',
  OWNERSHIP_TRANSFERRED: 'events.ownership.transferred',
  NEW_MESSAGE: 'events.new.message',
  DELETE_DOCUMENT: 'events.delete.document',
  RENAME_TEAM: 'events.rename.team',
  LIST_MOVED: 'events.list.move',
  LIST_UPDATED: 'events.list.update',
  LIST_CREATED: 'events.list.create',
  LIST_DELETED: 'events.list.delete',
  BOARD_CREATED: 'events.board.create',
  BOARD_DELETED: 'events.board.delete',
  BOARD_UPDATED: 'events.board.update',
};
