export enum PermissionKey {
    SEND_MESSAGES = 'SEND_MESSAGES',
    MANAGE_CHANNELS = 'MANAGE_CHANNELS',
    MANAGE_ROLES = 'MANAGE_ROLES',
    KICK_MEMBERS = 'KICK_MEMBERS',
    BAN_MEMBERS = 'BAN_MEMBERS',
    CREATE_INVITE = 'CREATE_INVITE',
    ATTACH_FILES = 'ATTACH_FILES',
    ADD_REACTIONS = 'ADD_REACTIONS',
    MENTION_EVERYONE = 'MENTION_EVERYONE',
    MANAGE_MESSAGES = 'MANAGE_MESSAGES',
    VIEW_CHANNELS = 'VIEW_CHANNELS',
}
