version: '3.9'
services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50050:50000-50050/udp"
    command: --config /etc/livekit.yml
    volumes:
      - ./livekit.yml:/etc/livekit.yml