export enum LabelErrorCode {
  LABEL_NOT_FOUND = 'LABEL_NOT_FOUND',
  LABEL_ALREADY_EXISTS = 'LABEL_ALREADY_EXISTS',
  INVALID_LABEL_DATA = 'INVALID_LABEL_DATA',
  UNAUTHORIZED_LABEL_ACCESS = 'UNAUTHORIZED_LABEL_ACCESS',
  LABEL_IN_USE = 'LABEL_IN_USE',
}
