export const TASK_PATTERNS = {
  FIND_ALL: 'task.findAll',
  FIND_ONE: 'task.findOne',
  FIND_ONE_BY_ID: 'task.findOneById',
  FIND_ALL_BY_PROJECT_ID: 'task.findAllByProjectId',
  FIND_BY_USER_ID: 'tasks.findByUserId',
  PROCESS_NLP: 'process_task_intent',
  CREATE: 'task.create',
  UPDATE: 'task.update',
  REMOVE: 'task.remove',
  FIND_GOOGLE_EVENTS: 'task.findGoogleEvents',
  ADD_FILES: 'task.addFiles',
  MOVE_INCOMPLETE_TASKS_TO_BACKLOG: 'task.moveIncompleteToBacklog',
  UNASSIGN_TASKS_FROM_SPRINT: 'task.unassignFromSprint',
};
