export const TASK_PATTERNS = {
  FIND_ALL: 'task.findAll',
  FIND_ONE: 'task.findOne',
  FIND_ONE_BY_ID: 'task.findOneById',
  FIND_ALL_BY_PROJECT_ID: 'task.findAllByProjectId',
  FIND_ALL_BY_TEAM_ID: 'task.findAllByTeam',
  FIND_BY_USER_ID: 'tasks.findByUserId',
  PROCESS_NLP: 'process_task_intent',
  CREATE: 'task.create',
  CREATE_MANY: 'task.createMany',
  DELETE_MANY: 'task.deleteMany',
  UPDATE: 'task.update',
  UPDATE_MANY: 'task.updateMany',
  REMOVE: 'task.remove',
  FIND_GOOGLE_EVENTS: 'task.findGoogleEvents',
  ADD_FILES: 'task.addFiles',
  MOVE_INCOMPLETE_TASKS_TO_BACKLOG: 'task.moveIncompleteToBacklog',
  UNASSIGN_TASKS_FROM_SPRINT: 'task.unassignFromSprint',
  FIND_ALL_LABELS_BY_TASK_ID: 'task.findAllLabelsByTaskId',
  GET_ALL_TASK_LABEL: 'task.getAllTaskLabel',
  HANDLE_LABEL_DELETED: 'task.handleLabelDeleted',
  REMOVE_FILE: 'task.removeFile',
  GET_STATS: 'task.getStats',
  SUGGEST_TASK: 'task.suggestTask',
  COMPLETE_SPRINT: 'task.completeSprint',
  SEND_NOTIFICATION: 'task.sendNotification',
  FIND_ALL_ASSIGN_TO_ME: 'task.findAllAssignToMe',
};
