export const REDIS_PATTERN = {
  STORE_REFRESH_TOKEN: 'redis.storeRefreshToken',
  STORE_GOOGLE_TOKEN: 'redis.storeGoogleToken',
  DELETE_REFRESH_TOKEN: 'redis.deleteRefreshToken',
  CLEAR_REFRESH_TOKENS: 'redis.clearRefreshTokens',
  GET_STORED_REFRESH_TOKEN: 'redis.getStoredRefreshToken',
  GET_GOOGLE_TOKEN: 'redis.getGoogleTokens',
  SET_LOCK_KEY: 'redis.setLockKey',
  NOTIFICATION: 'redis.notification',
  GET_USER_INFO: 'redis.getUserInfo',
  GET_USER_ROLE: 'redis.getUserRole',
  GET_MANY_USERS_INFO: 'redis.getManyUserInfo',
  SET_MANY_USERS_INFO: 'redis.setManyUserInfo',
  GET_TEAM_MEMBERS: 'redis.getTeamMember',
  GET_TEAM_MEMBERS_WITH_PROFILES: 'redis.getTeamMembersWithProfiles',
  SET_TEAM_MEMBERS: 'redis.setTeamMember',
  PUSH_MEETING_BUFFER: 'redis.pushToMeetingBuffer',
  POP_MEETING_BUFFER: 'redis.popMeetingBuffer',
  MARK_TOKEN_AS_USED: 'redis.markTokenAsUsed',
  IS_TOKEN_USED: 'redis.isTokenUsed',
  DELETE_LOCK_KEY: 'redis.deleteLockKey',
};
