name: 🚀 Frontend CI/CD (Next.js)

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  frontend:
    name: Frontend Build & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 20
            cache: "npm"
            cache-dependency-path: "frontend/package-lock.json" # Cache cho Frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint code
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Test frontend
        working-directory: ./frontend
        run: npm test --if-present
