export const NOTIFICATION_PATTERN = {
  SEND: 'notification.send',
  CREATE: 'notification.create',
  FIND: 'notification.find',
  UPDATE: 'notification.update',
  DELETE: 'notification.delete',
  MARK_AS_READ: 'notification.markAsRead',
  MARK_AS_UNREAD: 'notification.markAsUnread',
  MARK_ALL_AS_READ: 'notification.markAllAsRead',
  MARK_ALL_AS_UNREAD: 'notification.markAllAsUnread',
  PROCESS_DOCUMENT: 'notification.processDocument',
  TASK_ASSIGNED: 'notification.taskAssigned',
  TASK_UNASSIGNED: 'notification.taskUnassigned',
  TASK_UPDATED: 'notification.taskUpdated',
  TASK_DELETED: 'notification.taskDeleted', 
  EPIC_ASSIGNED: 'notification.epicAssigned',
  EPIC_UNASSIGNED: 'notification.epicUnassigned',
  EPIC_UPDATED: 'notification.epicUpdated',
  EPIC_DELETED: 'notification.epicDeleted',
  STATUS_UPDATED: 'notification.statusUpdated',
  LABEL_UPDATED: 'notification.labelUpdated',
  LABEL_DELETED: 'notification.labelDeleted',
  LABEL_CREATED: 'notification.labelCreated', 
  PROJECT_INVITATION: 'notification.projectInvitation',
  PROJECT_UPDATED: 'notification.projectUpdated',
  PROJECT_DELETED: 'notification.projectDeleted',
  PROJECT_CREATED: 'notification.projectCreated',
  PROJECT_ASSIGNED: 'notification.projectAssigned',
  PROJECT_UNASSIGNED: 'notification.projectUnassigned',
  
};
